version: "3"

networks:
  backend:

volumes:
  pgdata:

services:
  web:
    restart: always
    # Dockerfile의 위치를 지정
    build: ./Django-web 
    ports:
      - "8100:8000"
    volumes:
      - ./Django-web:/dog_demo
    networks:
      - backend
    env_file: .env
    command: "python manage.py runserver 0.0.0.0:8000"