33 lines (29 sloc)  492 Bytes

version: "3"

networks:
  backend:

volumes:
  pgdata:

services:
  web:
    restart: always
    # Dockerfile의 위치를 지정
    build: ./Django-web 
    ports:
      - "8100:8000"
    depends_on:
      - postgres
    volumes:
      - ./Django-web:/dog_demo
    networks:
      - backend
    env_file: .env
    command: './runserver.sh'